from TwitterFollowBot import TwitterBot

my_bot = TwitterBot()
my_bot.auto_fav("kanye")
my_bot.auto_fav("drake")
my_bot.auto_fav("rave")
my_bot.auto_fav("festival")
my_bot.auto_fav("#festival")
my_bot.auto_fav("#concert")
my_bot.auto_fav("concert")
my_bot.auto_fav("#plur")
my_bot.auto_fav("#onedirection")
my_bot.auto_fav("#1d")
my_bot.auto_fav("#justinbieber")
my_bot.auto_fav("one direction")
my_bot.auto_fav("justin bieber")
my_bot.auto_fav("dj")
my_bot.auto_fav("raver nation")
my_bot.auto_fav("rave babes")
my_bot.auto_fav("raver")
my_bot.auto_fav("#raver")
my_bot.auto_fav("#trap")
my_bot.auto_fav("#hardstyle")
my_bot.auto_fav("#plur")
my_bot.auto_fav("house music")
my_bot.auto_fav("deep house")
my_bot.auto_fav("trap music")
my_bot.auto_fav("#nowplaying")
my_bot.auto_fav("#np")
my_bot.auto_fav("mixtape")
my_bot.auto_fav("ovo radio")
my_bot.auto_fav("#ovoradio")
my_bot.auto_fav("views from the 6")
my_bot.auto_fav("#viewsfromthe6")
