from TwitterFollowBot import TwitterBot

my_bot = TwitterBot()
my_bot.auto_fav("snapchat stories")
my_bot.auto_fav("snapchat story")
my_bot.auto_fav("snap stories")
my_bot.auto_fav("snap story")
my_bot.auto_fav("ig")
my_bot.auto_fav("insta")
my_bot.auto_fav("its lit")
my_bot.auto_fav("it's lit")
my_bot.auto_fav("dope")
my_bot.auto_fav("and chill")
my_bot.auto_fav("fashion")
my_bot.auto_fav("#dope")
my_bot.auto_fav("dope")
my_bot.auto_fav("denver")
my_bot.auto_fav("#denver")
my_bot.auto_fav("#dallas")
my_bot.auto_fav("dallas")
my_bot.auto_fav("#soundcloud")
my_bot.auto_fav("soundcloud")
my_bot.auto_fav("spotify")
my_bot.auto_fav("#spotify")
my_bot.auto_fav("#discoverweekly")
my_bot.auto_fav("discover weekly")