from TwitterFollowBot import TwitterBot

my_bot = TwitterBot()
my_bot.auto_fav("beyond wonderland")
my_bot.auto_fav("sxsw")
my_bot.auto_fav("electric daisy carnival")
my_bot.auto_fav("lights all night")
my_bot.auto_fav("mad decent block party")
my_bot.auto_fav("moogfest")
my_bot.auto_fav("tomorrowland")
my_bot.auto_fav("tomorrowworld")
my_bot.auto_fav("ultra festival")
my_bot.auto_fav("ultra miami")
my_bot.auto_fav("electric zoo")
my_bot.auto_fav("life in color")
my_bot.auto_fav("#lic")
my_bot.auto_fav("edc vegas")
my_bot.auto_fav("electric forest")
my_bot.auto_fav("euphoria festival")
my_bot.auto_fav("hard summer")
my_bot.auto_fav("hard day of the dead")
my_bot.auto_fav("lightning in a bottle")
my_bot.auto_fav("mad decent boat party")
my_bot.auto_fav("lights all night")
my_bot.auto_fav("#lan2015")
